services:
  backend:
    build: 
      context: ./backend
      dockerfile: test.dockerfile
    image: test
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/var/www/app
    environment:
      MYSQL_DATABASE: 'pipeline'
      MYSQL_USER: 'pipeline'
      MYSQL_PASSWORD: '12345678'
    depends_on:
      - db
  db:
    image: 'mysql:9.1'
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'pipeline'
      MYSQL_USER: 'pipeline'
      MYSQL_PASSWORD: '12345678'
    volumes:
      - ./db_data:/var/lib/mysql
    